// svelte/src/routes/ListItem.svelte
<script>
	export let id = 0;
	export let desc = '';
	export let done = false;
	export let toggleDone = (id) => {};
	export let deleteTodo = (id) => {};
</script>

<div class="list-item">
	<h2>{id} - {desc}</h2>
	<span>Done? {String(done)}</span> <br />
	<div>
		<button type="button" on:click={() => toggleDone(id)}>Toggle done</button>
		<button type="button" class="danger" on:click={() => deleteTodo(id)}>Delete todo</button>
	</div>
</div>

<style>
	.list-item {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	h2 {
		font-weight: bold;
		font-size: 1.5rem;
	}

	button.danger {
		background-color: red;
		color: white;
	}

	button.danger:hover {
		background-color: darkred;
	}
</style>

// angular/src/app/list-item/list-item.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.css'],
})
export class ListItemComponent {
  @Input() id!: number;
  @Input() desc!: string;
  @Input() done!: boolean;
  @Input() toggleDone!: Function;
  @Input() deleteTodo!: Function;
}

<div class="list-item">
  <h2>{{ id }} - {{ desc }}</h2>
  <span>Done? {{ done.toString() }}</span
  ><br />
  <div>
    <button type="button" (click)="toggleDone(id)">Toggle done</button>
    <button type="button" class="danger" (click)="deleteTodo(id)">
      Delete todo
    </button>
  </div>
</div>
